site_name: Documentation Training

theme:
  name: material

nav:
  - Home: index.md
  - Login Flow: login_flow.md
  - Signup Flow: signup_flow.md
  - System Map: system_map.md


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - js/init-mermaid.js

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - admonition

plugins:
  - search
